name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: apt-update
      run: sudo apt update
    - name: apt-install-deps
      run: sudo apt install ninja-build mypy smlnj
    - name: mypy
      run: mypy --strict configure.py
    - name: configure
      run: ./configure.py
    - name: ninja
      run: ninja
